function [hu,hv,hw,hp] = plotVorticityNavierStokesEqns2d(x,y,q,t)
    DIM = 2;
    u = reshape(q(:,2),size(x)); 
    v = reshape(q(:,3),size(y));
    U = sqrt(u.*u + v.*v);
    colormap jet;
    subplot(221); 
        [hu] = contourf(x,y,u);
        view(DIM); 
        title(sprintf('$u(x,y,t = %1.2f)$',t), Interpreter='latex');
        xlabel('$x$', Interpreter='latex'); 
        ylabel('$y$', Interpreter='latex');
        shading interp; 
        clim([-1,1]);
        colorbar;
    subplot(222); 
        [hv] = contourf(x,y,v);
        view(DIM); 
        title(sprintf('$v(x,y,t = %1.2f)$',t), Interpreter='latex');
        xlabel('$x$', Interpreter='latex'); 
        ylabel('$y$', Interpreter='latex');
        shading interp; 
        clim([-1,1]);
        colorbar;
    subplot(223); 
        [hw] = surf(x,y,U);
        view(DIM); 
        title(sprintf('$|\\vec{v}|(x,y,t = %1.2f)$',t), Interpreter='latex');
        xlabel('$x$', Interpreter='latex'); 
        ylabel('$y$', Interpreter='latex');
        shading interp; 
        clim([0,1]);
        colorbar;
    subplot(224); 
        [hp] = quiver(x,y,u,v);
        view(DIM); 
        title(sprintf('$\\vec v = \\nabla\\times\\vec\\psi$',t), Interpreter='latex');
        xlabel('$x$', Interpreter='latex'); 
        ylabel('$y$', Interpreter='latex');
end