function [hu,hv,hw,hp] = plotVorticityNavierStokesEqns3d(x,y,z,q,t)
    DIM = 3;
    u = reshape(q(:,2),size(x));
    v = reshape(q(:,3),size(y));
    w = reshape(q(:,4),size(z));
    p = reshape(q(:,5),size(x));
    colormap jet;
    subplot(221); 
        [hu] = slice(x,y,z,u,0.86,0.86,0.08);
        view(DIM); 
        title(sprintf('$u(x,y,t = %1.2f)$',t), Interpreter='latex');
        xlabel('$x$', Interpreter='latex'); 
        ylabel('$y$', Interpreter='latex');
        zlabel('$z$', Interpreter='latex');
        shading interp; 
        clim([-1.2,1.2]);
        colorbar;
    subplot(222); 
        [hv] = slice(x,y,z,v,0.86,0.86,0.08);
        view(DIM); 
        title(sprintf('$v(x,y,t = %1.2f)$',t), Interpreter='latex');
        xlabel('$x$', Interpreter='latex'); 
        ylabel('$y$', Interpreter='latex');
        zlabel('$z$', Interpreter='latex');
        shading interp; 
        clim([-1.2,1.2]);
        colorbar;
    subplot(223); 
        [hw] = slice(x,y,z,w,0.86,0.86,0.08);
        view(DIM); 
        title(sprintf('$v(x,y,t = %1.2f)$',t), Interpreter='latex');
        xlabel('$x$', Interpreter='latex'); 
        ylabel('$y$', Interpreter='latex');
        zlabel('$z$', Interpreter='latex');
        shading interp; 
        clim([-1.2,1.2]);
        colorbar;
    subplot(224); 
        [hp] = slice(x,y,z,p,0.86,0.86,0.08);
        view(DIM); 
        title(sprintf('$\\wp(x,y,t = %1.2f)$',t), Interpreter='latex');
        xlabel('$x$', Interpreter='latex'); 
        ylabel('$y$', Interpreter='latex');
        zlabel('$z$', Interpreter='latex');
        shading interp; 
        clim([-1.3,0.1]);
        colorbar;
        % Iso-surface 
        level = -0.02;
        hold on;
            isosurface(x,y,z,p,level);
            patchSurface = patch(isosurface(x,y,z,p,level));
            isonormals(x,y,z,p,patchSurface);
            set(patchSurface,'FaceColor',[0.9 0.9 0.9]);
            set(patchSurface,'EdgeColor','none');
            camlight; lighting gouraud;
        hold off;
end